### ISSUE TITLE
Dashboard Config. button

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/Widget-Manager#1]
The dashboard cog configuration button does not work.

**Comment by Nicola1971** [comment]
evo version?

**Comment by risingisland** [comment]
1.0.4rc2 with latest Flat theme
Tested with FF & Chrome

**Comment by Nicola1971** [comment]
i've fixed for 1.4rc2 5 days ago, https://github.com/Nicola1971/Widget-Manager/commit/f27587c16b74808a8264d40b432d1adfcd7672c3

**Comment by risingisland** [comment]
I stand corrected. That one slipped by me. Thanks
