### ISSUE TITLE
EVO Parse Error

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/Widget-Manager#2]
@Nicola1971 
Receiving this Parse Error for any role other than Admin:
![My Evolution Site   EVO CMS Manager ](https://user-images.githubusercontent.com/6113504/54073302-6b4c0480-427d-11e9-8cae-b8ebd2067ed1.png)

If I de-activate plugin, dash works fine.
Using Evo v1.47 & v1.48

**Comment by risingisland** [comment]
Upon further testing, I found that the problem revolves around the Role Permissions, "Edit Plugins".
If this is enabled, everything works fine.
Not sure if this is a plugin bug, or an Evo bug?

**Comment by Nicola1971** [comment]
thanks @risingisland .
After a first check, i can confirm the issue in the edit plugin condition part (for the config button):
```if($modx->hasPermission('edit_plugin')) {...```
but i use this code in all my widgets and always worked fine.

Just tested Evo Stats and the config button works without errors

need further investigation

**Comment by risingisland** [comment]
Maybe could be changed to `exec_module`  or `edit_document` ?

**Comment by risingisland** [comment]
I am not sure if there is a specific reason for "edit_plugin"?
For my instance, I changed this to "home".

**Comment by Nicola1971** [comment]
> I am not sure if there is a specific reason for "edit_plugin"?

 only to hide the "settings" button from the user who has no permissions to modify the dashboard

**Comment by risingisland** [comment]
Ah, ok.

**Comment by risingisland** [comment]
Until a solution can be found, I will change to `if($modx->hasPermission('home')) {...` and add `style="display:none;` to the container.
If the plugin config needs to be changed, I can do this the old fashioned way via the menu  :wink:

**Comment by Nicola1971** [comment]
moved the button to a placeholder and seeems fixed the issue.
please try the dev branch version and confirm 

https://github.com/Nicola1971/Widget-Manager/tree/dev

**Comment by risingisland** [comment]
This seem to do the trick. 
I tried it as an update as well as a fresh install. 
Both seem to work as expected.
Thanks for the quick fix. :+1:

**Comment by Nicola1971** [comment]
thanks to you for reporting the problem :)
